circuit_index:
    path:     /
    defaults: { _controller: "AdminBundle:Circuit:index" }
    methods:  GET

circuit_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Circuit:show" }
    methods:  GET

circuit_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Circuit:new" }
    methods:  [GET, POST]

circuit_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Circuit:edit" }
    methods:  [GET, POST]

circuit_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Circuit:delete" }
    methods:  DELETE
